"""Reloading all models

Revision ID: 12095f1f086d
Revises: e804866392fe
Create Date: 2026-04-11 18:34:58.478249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "12095f1f086d"
down_revision: Union[str, None] = "e804866392fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_security_questions_question"),
        table_name="security_questions",
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_security_questions_question"),
        "security_questions",
        ["question"],
        unique=True,
        schema="railmind_be",
    )
    op.drop_index(op.f("ix_users_email"), table_name="users", schema="railmind_be")
    op.drop_index(op.f("ix_users_role"), table_name="users", schema="railmind_be")
    op.drop_index(op.f("ix_users_username"), table_name="users", schema="railmind_be")
    op.create_index(
        op.f("ix_railmind_be_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_users_role"),
        "users",
        ["role"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_users_username"), table_name="users", schema="railmind_be"
    )
    op.drop_index(
        op.f("ix_railmind_be_users_role"), table_name="users", schema="railmind_be"
    )
    op.drop_index(
        op.f("ix_railmind_be_users_email"), table_name="users", schema="railmind_be"
    )
    op.create_index(
        op.f("ix_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_users_role"), "users", ["role"], unique=False, schema="railmind_be"
    )
    op.create_index(
        op.f("ix_users_email"), "users", ["email"], unique=True, schema="railmind_be"
    )
    op.drop_index(
        op.f("ix_railmind_be_security_questions_question"),
        table_name="security_questions",
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_security_questions_question"),
        "security_questions",
        ["question"],
        unique=True,
        schema="railmind_be",
    )
    # ### end Alembic commands ###
