"""google oauth account table added

Revision ID: 405516e47187
Revises: db9e70c82584
Create Date: 2026-06-05 09:14:15.012245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "405516e47187"
down_revision: Union[str, None] = "db9e70c82584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth_accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=False),
        sa.Column("picture_url", sa.String(length=512), nullable=True),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_user_id",
            name="uq_user_oauth_accounts_provider_provider_user_id",
        ),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_user_oauth_accounts_user_id_provider"
        ),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_user_oauth_accounts_user_id"),
        "user_oauth_accounts",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_user_oauth_accounts_user_id"),
        table_name="user_oauth_accounts",
        schema="railmind_be",
    )
    op.drop_table("user_oauth_accounts", schema="railmind_be")
    # ### end Alembic commands ###
