"""payment and refund table added new

Revision ID: 42a673a1ace7
Revises: bbf4df0a8c98
Create Date: 2026-05-30 18:52:22.147078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "42a673a1ace7"
down_revision: Union[str, None] = "bbf4df0a8c98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "UPI",
                "CARD",
                "NETBANKING",
                "WALLET",
                "EMI",
                "PAY_LATER",
                "OTHER",
                name="payment_method_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                "REFUNDED",
                name="payment_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "gateway", sa.Enum("RAZORPAY", name="payment_gateway_enum"), nullable=False
        ),
        sa.Column("gateway_order_id", sa.String(length=100), nullable=False),
        sa.Column("gateway_payment_id", sa.String(length=100), nullable=True),
        sa.Column("gateway_signature", sa.String(length=255), nullable=True),
        sa.Column(
            "gateway_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("initiated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["railmind_be.bookings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_payments_booking_id"),
        "payments",
        ["booking_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_payments_gateway_order_id"),
        "payments",
        ["gateway_order_id"],
        unique=True,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_payments_gateway_payment_id"),
        "payments",
        ["gateway_payment_id"],
        unique=True,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_payments_payment_status"),
        "payments",
        ["payment_status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "refunds",
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "deduction_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("original_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "refund_status",
            sa.Enum(
                "INITIATED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                "CANCELLED",
                name="refund_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "refund_reason",
            sa.Enum(
                "USER_CANCELLATION",
                "TRAIN_CANCELLED",
                "WAITLIST_DROPPED",
                "PAYMENT_DISPUTE",
                "SYSTEM_ERROR",
                "ADMIN_OVERRIDE",
                name="refund_reason_enum",
            ),
            nullable=False,
        ),
        sa.Column("refund_notes", sa.Text(), nullable=True),
        sa.Column("gateway_refund_id", sa.String(length=100), nullable=True),
        sa.Column(
            "gateway_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("initiated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["railmind_be.bookings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["railmind_be.payments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_refunds_booking_id"),
        "refunds",
        ["booking_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_refunds_gateway_refund_id"),
        "refunds",
        ["gateway_refund_id"],
        unique=True,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_refunds_payment_id"),
        "refunds",
        ["payment_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_refunds_refund_status"),
        "refunds",
        ["refund_status"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_refunds_refund_status"),
        table_name="refunds",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_refunds_payment_id"),
        table_name="refunds",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_refunds_gateway_refund_id"),
        table_name="refunds",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_refunds_booking_id"),
        table_name="refunds",
        schema="railmind_be",
    )
    op.drop_table("refunds", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_payments_payment_status"),
        table_name="payments",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_payments_gateway_payment_id"),
        table_name="payments",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_payments_gateway_order_id"),
        table_name="payments",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_payments_booking_id"),
        table_name="payments",
        schema="railmind_be",
    )
    op.drop_table("payments", schema="railmind_be")
    # ### end Alembic commands ###
