"""Passengers and users and train relationship commented

Revision ID: 71193928cefa
Revises: 12095f1f086d
Create Date: 2026-04-11 18:59:10.140839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "71193928cefa"
down_revision: Union[str, None] = "12095f1f086d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
