"""profile photo column added in the user_profiles table

Revision ID: 73bcc9fb7621
Revises: 1e2a4591baf5
Create Date: 2026-05-30 10:30:44.558007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "73bcc9fb7621"
down_revision: Union[str, None] = "1e2a4591baf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column("profile_photo", sa.Text(), nullable=True),
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "profile_photo", schema="railmind_be")
    # ### end Alembic commands ###
