"""Payment Module Enums added

Revision ID: 764ed4e0db6b
Revises: 42a673a1ace7
Create Date: 2026-06-02 09:22:04.828287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "764ed4e0db6b"
down_revision: Union[str, None] = "42a673a1ace7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    # ── payment_method_enum ──────────────────────────────────────────────
    payment_method_enum = sa.Enum(
        "UPI",
        "CARD",
        "NETBANKING",
        "WALLET",
        "EMI",
        "PAY_LATER",
        "OTHER",
        name="payment_method_enum",
        schema="railmind_be",
    )
    payment_method_enum.create(bind, checkfirst=True)

    # ── payment_status_enum ──────────────────────────────────────────────
    payment_status_enum = sa.Enum(
        "PENDING",
        "PROCESSING",
        "SUCCESS",
        "FAILED",
        "REFUNDED",
        name="payment_status_enum",
        schema="railmind_be",
    )
    payment_status_enum.create(bind, checkfirst=True)

    # ── payment_gateway_enum ─────────────────────────────────────────────
    payment_gateway_enum = sa.Enum(
        "RAZORPAY",
        "MOCK",
        name="payment_gateway_enum",
        schema="railmind_be",
    )
    payment_gateway_enum.create(bind, checkfirst=True)

    # Ensure MOCK is present if enum already existed without it
    op.execute(
        "ALTER TYPE railmind_be.payment_gateway_enum ADD VALUE IF NOT EXISTS 'MOCK'"
    )

    # ── refund_status_enum ───────────────────────────────────────────────
    refund_status_enum = sa.Enum(
        "INITIATED",
        "PROCESSING",
        "PROCESSED",
        "FAILED",
        "CANCELLED",
        name="refund_status_enum",
        schema="railmind_be",
    )
    refund_status_enum.create(bind, checkfirst=True)

    # ── refund_reason_enum ───────────────────────────────────────────────
    refund_reason_enum = sa.Enum(
        "USER_CANCELLATION",
        "TRAIN_CANCELLED",
        "WAITLIST_DROPPED",
        "PAYMENT_DISPUTE",
        "SYSTEM_ERROR",
        "ADMIN_OVERRIDE",
        name="refund_reason_enum",
        schema="railmind_be",
    )
    refund_reason_enum.create(bind, checkfirst=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
