"""Add User Role table

Revision ID: 8269c9099bca
Revises: 618b65d5cef1
Create Date: 2026-04-04 10:48:13.915986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8269c9099bca'
down_revision: Union[str, None] = '618b65d5cef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_questions_question'), table_name='security_questions')
    op.create_index(op.f('ix_railmind_be_security_questions_question'), 'security_questions', ['question'], unique=True, schema='railmind_be')
    op.drop_constraint(op.f('user_contacts_user_id_fkey'), 'user_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'user_contacts', 'users', ['user_id'], ['id'], source_schema='railmind_be', referent_schema='railmind_be', ondelete='CASCADE')
    op.drop_constraint(op.f('user_kyc_user_id_fkey'), 'user_kyc', type_='foreignkey')
    op.create_foreign_key(None, 'user_kyc', 'users', ['user_id'], ['id'], source_schema='railmind_be', referent_schema='railmind_be', ondelete='CASCADE')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], source_schema='railmind_be', referent_schema='railmind_be', ondelete='CASCADE')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.execute("UPDATE users SET role = 'USER'")
    op.alter_column('users', 'role', nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_railmind_be_users_email'), 'users', ['email'], unique=True, schema='railmind_be')
    op.create_index(op.f('ix_railmind_be_users_role'), 'users', ['role'], unique=False, schema='railmind_be')
    op.create_index(op.f('ix_railmind_be_users_username'), 'users', ['username'], unique=True, schema='railmind_be')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_railmind_be_users_username'), table_name='users', schema='railmind_be')
    op.drop_index(op.f('ix_railmind_be_users_role'), table_name='users', schema='railmind_be')
    op.drop_index(op.f('ix_railmind_be_users_email'), table_name='users', schema='railmind_be')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'user_profiles', schema='railmind_be', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_kyc', schema='railmind_be', type_='foreignkey')
    op.create_foreign_key(op.f('user_kyc_user_id_fkey'), 'user_kyc', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_contacts', schema='railmind_be', type_='foreignkey')
    op.create_foreign_key(op.f('user_contacts_user_id_fkey'), 'user_contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_railmind_be_security_questions_question'), table_name='security_questions', schema='railmind_be')
    op.create_index(op.f('ix_security_questions_question'), 'security_questions', ['question'], unique=True)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
