"""add train_type and runs_on_days to trains

Revision ID: 9b3cd6f8472d
Revises: f7711f7d189e
Create Date: 2026-04-05 12:33:03.505895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b3cd6f8472d'
down_revision: Union[str, None] = 'f7711f7d189e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('train_type', sa.String(length=30), nullable=False, server_default='unknown'), schema='railmind_be')
    op.add_column('trains', sa.Column('runs_on_days', postgresql.ARRAY(sa.String()), nullable=False, comment="Days train runs e.g. ['mon','tue','wed']", server_default='{}'), schema='railmind_be')
    op.create_index(op.f('ix_railmind_be_trains_train_type'), 'trains', ['train_type'], unique=False, schema='railmind_be')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_railmind_be_trains_train_type'), table_name='trains', schema='railmind_be')
    op.drop_column('trains', 'runs_on_days', schema='railmind_be')
    op.drop_column('trains', 'train_type', schema='railmind_be')
    # ### end Alembic commands ###
