"""booking retry request model added

Revision ID: 9ed01d783bfe
Revises: f82eed385649
Create Date: 2026-05-01 20:13:35.094613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "9ed01d783bfe"
down_revision: Union[str, None] = "f82eed385649"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_retry_request",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "failure_reason",
            sa.Enum(
                "SEAT_UNAVAILABLE",
                "PAYMENT_TIMEOUT",
                name="retry_failure_reason",
                schema="railmind_be",
            ),
            nullable=False,
        ),
        sa.Column("original_payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RETRYING",
                "SUCCESS",
                "EXHAUSTED",
                name="booking_retry_status",
                schema="railmind_be",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success_booking_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["railmind_be.bookings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["success_booking_id"], ["railmind_be.bookings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_retry_request_booking_id"),
        "booking_retry_request",
        ["booking_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_retry_request_next_retry_at"),
        "booking_retry_request",
        ["next_retry_at"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_retry_request_status"),
        "booking_retry_request",
        ["status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_retry_request_user_id"),
        "booking_retry_request",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_booking_retry_request_user_id"),
        table_name="booking_retry_request",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_booking_retry_request_status"),
        table_name="booking_retry_request",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_booking_retry_request_next_retry_at"),
        table_name="booking_retry_request",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_booking_retry_request_booking_id"),
        table_name="booking_retry_request",
        schema="railmind_be",
    )
    op.drop_table("booking_retry_request", schema="railmind_be")
    # ### end Alembic commands ###
