"""popular destinations image_url added

Revision ID: a7d2e9c4b1f6
Revises: f1c5d8e3a7b2
Create Date: 2026-07-04 00:00:00.000000

Weekly carousel city images — generated by nano-banana-2 (Replicate), stored in
Supabase (railmind/trending/weekly_crousel_city_images), reused across weeks.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.config import settings

revision: str = "a7d2e9c4b1f6"
down_revision: Union[str, None] = "f1c5d8e3a7b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = settings.DB_SCHEMA


def upgrade() -> None:
    op.add_column(
        "popular_destinations",
        sa.Column("image_url", sa.String(length=500), nullable=True),
        schema=SCHEMA,
    )


def downgrade() -> None:
    op.drop_column("popular_destinations", "image_url", schema=SCHEMA)
