"""add station_clusters tables

Revision ID: ae53d1730e55
Revises: d75f478d3af9
Create Date: 2026-06-16 07:20:13.152960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "ae53d1730e55"
down_revision: Union[str, None] = "d75f478d3af9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station_clusters",
        sa.Column("cluster_code", sa.String(length=20), nullable=False),
        sa.Column("cluster_name", sa.String(length=100), nullable=False),
        sa.Column("primary_station_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["primary_station_id"],
            ["railmind_be.stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_code"),
        schema="railmind_be",
    )
    op.create_table(
        "station_cluster_members",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"], ["railmind_be.station_clusters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["railmind_be.stations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id", "station_id", name="uq_cluster_station"),
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_cluster_members", schema="railmind_be")
    op.drop_table("station_clusters", schema="railmind_be")
    # ### end Alembic commands ###
