"""security question and security ans hash set to nullable =true

Revision ID: ba7e7b6309d3
Revises: f3d85bcf6fc9
Create Date: 2026-06-05 09:58:39.770370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ba7e7b6309d3"
down_revision: Union[str, None] = "f3d85bcf6fc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "security_question", nullable=True, schema="railmind_be")
    op.alter_column(
        "users", "security_answer_hash", nullable=True, schema="railmind_be"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "security_answer_hash", nullable=False, schema="railmind_be"
    )
    op.alter_column("users", "security_question", nullable=False, schema="railmind_be")
    # ### end Alembic commands ###
