"""payment and refund table added

Revision ID: bbf4df0a8c98
Revises: 73bcc9fb7621
Create Date: 2026-05-30 18:41:15.413282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bbf4df0a8c98"
down_revision: Union[str, None] = "73bcc9fb7621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_railmind_be_bookings_destination_station_id"),
        "bookings",
        ["destination_station_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_bookings_source_station_id"),
        "bookings",
        ["source_station_id"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_bookings_source_station_id"),
        table_name="bookings",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_bookings_destination_station_id"),
        table_name="bookings",
        schema="railmind_be",
    )
    # ### end Alembic commands ###
