"""Add passengers table

Revision ID: d1adb6832e68
Revises: e1849113095a
Create Date: 2026-04-14 09:12:27.475430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d1adb6832e68"
down_revision: Union[str, None] = "e1849113095a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passengers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=False),
        sa.Column("id_type", sa.String(length=20), nullable=True),
        sa.Column("id_number", sa.String(length=30), nullable=True),
        sa.Column("berth_preference", sa.String(length=5), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "is_primary", name="uq_passengers_user_primary"),
        schema="railmind_be",
    )
    op.create_index(
        "ix_passengers_user_id",
        "passengers",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_passengers_user_id"),
        "passengers",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_foreign_key(
        None,
        "booking_passengers",
        "passengers",
        ["passenger_id"],
        ["id"],
        source_schema="railmind_be",
        referent_schema="railmind_be",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "booking_passengers", schema="railmind_be", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_railmind_be_passengers_user_id"),
        table_name="passengers",
        schema="railmind_be",
    )
    op.drop_index(
        "ix_passengers_user_id", table_name="passengers", schema="railmind_be"
    )
    op.drop_table("passengers", schema="railmind_be")
    # ### end Alembic commands ###
