"""search history table created

Revision ID: d75f478d3af9
Revises: f9958c7986f2
Create Date: 2026-06-15 22:43:44.095471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d75f478d3af9"
down_revision: Union[str, None] = "f9958c7986f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_histories",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_station_id", sa.UUID(), nullable=False),
        sa.Column("destination_station_id", sa.UUID(), nullable=False),
        sa.Column("journey_date", sa.Date(), nullable=True),
        sa.Column("train_class", sa.String(length=5), nullable=True),
        sa.Column("quota", sa.String(length=5), nullable=True),
        sa.Column("searched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destination_station_id"], ["railmind_be.stations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_station_id"], ["railmind_be.stations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "source_station_id",
            "destination_station_id",
            name="uq_search_user_route",
        ),
        schema="railmind_be",
    )
    op.create_index(
        "ix_search_histories_user_searched",
        "search_histories",
        ["user_id", "searched_at"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_search_histories_user_searched",
        table_name="search_histories",
        schema="railmind_be",
    )
    op.drop_table("search_histories", schema="railmind_be")
    # ### end Alembic commands ###
