"""google oauth account table added

Revision ID: db9e70c82584
Revises: b6c57be41a5b
Create Date: 2026-06-05 09:12:50.454831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "db9e70c82584"
down_revision: Union[str, None] = "b6c57be41a5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", nullable=True, schema="railmind_be")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", nullable=False, schema="railmind_be")
    # ### end Alembic commands ###
