"""Base Model Timestamp Updated

Revision ID: e0ce05b3d5ed
Revises: cdee72e2d338
Create Date: 2026-04-15 09:45:06.315699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e0ce05b3d5ed"
down_revision: Union[str, None] = "cdee72e2d338"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix_passengers_one_primary_per_user"),
        table_name="passengers",
        schema="railmind_be",
        postgresql_where="(is_primary = true)",
    )
    op.create_unique_constraint(
        "uq_passengers_user_primary",
        "passengers",
        ["user_id", "is_primary"],
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_passengers_user_primary", "passengers", schema="railmind_be", type_="unique"
    )
    op.create_index(
        op.f("uix_passengers_one_primary_per_user"),
        "passengers",
        ["user_id"],
        unique=True,
        schema="railmind_be",
        postgresql_where="(is_primary = true)",
    )
    # ### end Alembic commands ###
