"""Fare Rules Model Added

Revision ID: e1849113095a
Revises: 71193928cefa
Create Date: 2026-04-12 14:53:10.800315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e1849113095a"
down_revision: Union[str, None] = "71193928cefa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fare_rules",
        sa.Column("train_class", sa.String(length=5), nullable=False),
        sa.Column("base_fare_per_km", sa.Float(), nullable=False),
        sa.Column("reservation_charge", sa.SmallInteger(), nullable=False),
        sa.Column("superfast_min_charge", sa.SmallInteger(), nullable=False),
        sa.Column("tatkal_multiplier", sa.Float(), nullable=False),
        sa.Column("premium_tatkal_min_multiplier", sa.Float(), nullable=False),
        sa.Column("premium_tatkal_max_multiplier", sa.Float(), nullable=False),
        sa.Column("gst_percent", sa.Float(), nullable=False),
        sa.Column("minimum_fare", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_class"),
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fare_rules", schema="railmind_be")
    # ### end Alembic commands ###
