"""Booking and waiting list model added v2

Revision ID: e804866392fe
Revises: fdbf0c2f2814
Create Date: 2026-04-08 09:27:45.141970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e804866392fe"
down_revision: Union[str, None] = "fdbf0c2f2814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("train_id", sa.UUID(), nullable=False),
        sa.Column("pnr_number", sa.String(length=10), nullable=False),
        sa.Column("booking_status", sa.String(length=20), nullable=False),
        sa.Column("journey_date", sa.Date(), nullable=False),
        sa.Column("source_station_id", sa.UUID(), nullable=False),
        sa.Column("destination_station_id", sa.UUID(), nullable=False),
        sa.Column("train_class", sa.String(length=5), nullable=False),
        sa.Column("quota", sa.String(length=5), nullable=False),
        sa.Column("total_fare", sa.Float(), nullable=False),
        sa.Column("booked_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["destination_station_id"], ["railmind_be.stations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_station_id"], ["railmind_be.stations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["train_id"], ["railmind_be.trains.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pnr_number"),
        schema="railmind_be",
    )
    op.create_index(
        "ix_bookings_user_status",
        "bookings",
        ["user_id", "booking_status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_bookings_booking_status"),
        "bookings",
        ["booking_status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_bookings_journey_date"),
        "bookings",
        ["journey_date"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_bookings_train_id"),
        "bookings",
        ["train_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_bookings_user_id"),
        "bookings",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "booking_passengers",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("passenger_id", sa.UUID(), nullable=False),
        sa.Column("seat_id", sa.UUID(), nullable=True),
        sa.Column("seat_inventory_id", sa.UUID(), nullable=False),
        sa.Column("berth_preference", sa.String(length=5), nullable=False),
        sa.Column("allotted_berth", sa.String(length=5), nullable=True),
        sa.Column("passenger_status", sa.String(length=5), nullable=False),
        sa.Column("fare", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["railmind_be.bookings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["railmind_be.seats.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["seat_inventory_id"],
            ["railmind_be.seat_inventories.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="railmind_be",
    )
    op.create_index(
        "ix_bkng_passengers_inv_status",
        "booking_passengers",
        ["seat_inventory_id", "passenger_status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_passengers_booking_id"),
        "booking_passengers",
        ["booking_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_passengers_passenger_id"),
        "booking_passengers",
        ["passenger_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_booking_passengers_passenger_status"),
        "booking_passengers",
        ["passenger_status"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "rac_slots",
        sa.Column("seat_inventory_id", sa.UUID(), nullable=False),
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("seat_id", sa.UUID(), nullable=False),
        sa.Column("slot_number", sa.SmallInteger(), nullable=False),
        sa.Column("passenger_1_booking_passenger_id", sa.UUID(), nullable=True),
        sa.Column("passenger_2_booking_passenger_id", sa.UUID(), nullable=True),
        sa.Column("is_full", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"], ["railmind_be.coaches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["passenger_1_booking_passenger_id"],
            ["railmind_be.booking_passengers.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["passenger_2_booking_passenger_id"],
            ["railmind_be.booking_passengers.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["railmind_be.seats.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["seat_inventory_id"],
            ["railmind_be.seat_inventories.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seat_inventory_id", "seat_id", name="uq_rac_slots_inv_seat"
        ),
        sa.UniqueConstraint(
            "seat_inventory_id", "slot_number", name="uq_rac_slots_inv_slot"
        ),
        schema="railmind_be",
    )
    op.create_index(
        "ix_rac_slots_available",
        "rac_slots",
        ["seat_inventory_id", "slot_number"],
        unique=False,
        schema="railmind_be",
        postgresql_where="is_full = false",
    )
    op.create_index(
        op.f("ix_railmind_be_rac_slots_seat_inventory_id"),
        "rac_slots",
        ["seat_inventory_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "waitlists",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("booking_passenger_id", sa.UUID(), nullable=False),
        sa.Column("seat_inventory_id", sa.UUID(), nullable=False),
        sa.Column("train_class", sa.String(length=5), nullable=False),
        sa.Column("quota", sa.String(length=5), nullable=False),
        sa.Column("wl_type", sa.String(length=10), nullable=False),
        sa.Column("booking_position", sa.SmallInteger(), nullable=False),
        sa.Column("current_position", sa.SmallInteger(), nullable=False),
        sa.Column("source_station_id", sa.UUID(), nullable=False),
        sa.Column("destination_station_id", sa.UUID(), nullable=False),
        sa.Column("is_promoted", sa.Boolean(), nullable=False),
        sa.Column("promoted_to", sa.String(length=5), nullable=True),
        sa.Column("promoted_at", sa.DateTime(), nullable=True),
        sa.Column("is_auto_cancelled", sa.Boolean(), nullable=False),
        sa.Column("auto_cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["railmind_be.bookings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["booking_passenger_id"],
            ["railmind_be.booking_passengers.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["destination_station_id"], ["railmind_be.stations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["seat_inventory_id"],
            ["railmind_be.seat_inventories.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_station_id"], ["railmind_be.stations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_passenger_id"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_waitlists_booking_id"),
        "waitlists",
        ["booking_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_waitlists_seat_inventory_id"),
        "waitlists",
        ["seat_inventory_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        "ix_waitlists_active_by_inventory",
        "waitlists",
        ["seat_inventory_id"],
        unique=False,
        schema="railmind_be",
        postgresql_where="is_promoted = false AND is_auto_cancelled = false",
    )
    op.create_index(
        "ix_waitlists_promotable",
        "waitlists",
        ["seat_inventory_id", "wl_type", "current_position"],
        unique=False,
        schema="railmind_be",
        postgresql_where="is_promoted = false AND is_auto_cancelled = false",
    )
    op.create_index(
        "ix_waitlists_wl_type_position",
        "waitlists",
        ["wl_type", "current_position"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_waitlists_wl_type_position", table_name="waitlists", schema="railmind_be"
    )
    op.drop_index(
        "ix_waitlists_promotable",
        table_name="waitlists",
        schema="railmind_be",
        postgresql_where="is_promoted = false AND is_auto_cancelled = false",
    )
    op.drop_index(
        "ix_waitlists_active_by_inventory",
        table_name="waitlists",
        schema="railmind_be",
        postgresql_where="is_promoted = false AND is_auto_cancelled = false",
    )
    op.drop_index(
        op.f("ix_railmind_be_waitlists_seat_inventory_id"),
        table_name="waitlists",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_waitlists_booking_id"),
        table_name="waitlists",
        schema="railmind_be",
    )
    op.drop_table("waitlists", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_rac_slots_seat_inventory_id"),
        table_name="rac_slots",
        schema="railmind_be",
    )
    op.drop_index(
        "ix_rac_slots_available",
        table_name="rac_slots",
        schema="railmind_be",
        postgresql_where="is_full = false",
    )
    op.drop_table("rac_slots", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_booking_passengers_passenger_status"),
        table_name="booking_passengers",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_booking_passengers_passenger_id"),
        table_name="booking_passengers",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_booking_passengers_booking_id"),
        table_name="booking_passengers",
        schema="railmind_be",
    )
    op.drop_index(
        "ix_bkng_passengers_inv_status",
        table_name="booking_passengers",
        schema="railmind_be",
    )
    op.drop_table("booking_passengers", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_bookings_user_id"),
        table_name="bookings",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_bookings_train_id"),
        table_name="bookings",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_bookings_journey_date"),
        table_name="bookings",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_bookings_booking_status"),
        table_name="bookings",
        schema="railmind_be",
    )
    op.drop_index(
        "ix_bookings_user_status", table_name="bookings", schema="railmind_be"
    )
    op.drop_table("bookings", schema="railmind_be")
    # ### end Alembic commands ###
