"""users table passowrd set to NULABLE = True and Role set to NULLABLE=False

Revision ID: f3d85bcf6fc9
Revises: 405516e47187
Create Date: 2026-06-05 09:55:05.617844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f3d85bcf6fc9"
down_revision: Union[str, None] = "405516e47187"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", nullable=True, schema="railmind_be")
    op.alter_column("users", "role", nullable=False, schema="railmind_be")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", nullable=True, schema="railmind_be")
    op.alter_column("users", "password", nullable=False, schema="railmind_be")
    # ### end Alembic commands ###
