"""user behaviour logs model added

Revision ID: f82eed385649
Revises: 84b57c23385e
Create Date: 2026-04-30 18:29:16.315999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f82eed385649"
down_revision: Union[str, None] = "84b57c23385e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_behavior_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column(
            "action_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["railmind_be.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_user_behavior_logs_action_type"),
        "user_behavior_logs",
        ["action_type"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_user_behavior_logs_session_id"),
        "user_behavior_logs",
        ["session_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_user_behavior_logs_user_id"),
        "user_behavior_logs",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_passengers_user_id"), table_name="passengers", schema="railmind_be"
    )
    op.create_index(
        op.f("ix_railmind_be_passengers_user_id"),
        "passengers",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_passengers_user_id"),
        table_name="passengers",
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_passengers_user_id"),
        "passengers",
        ["user_id"],
        unique=False,
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_user_behavior_logs_user_id"),
        table_name="user_behavior_logs",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_user_behavior_logs_session_id"),
        table_name="user_behavior_logs",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_user_behavior_logs_action_type"),
        table_name="user_behavior_logs",
        schema="railmind_be",
    )
    op.drop_table("user_behavior_logs", schema="railmind_be")
    # ### end Alembic commands ###
