"""Booking and waiting list model added

Revision ID: fdbf0c2f2814
Revises: 9b3cd6f8472d
Create Date: 2026-04-08 09:00:07.945352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "fdbf0c2f2814"
down_revision: Union[str, None] = "9b3cd6f8472d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaches",
        sa.Column("train_id", sa.UUID(), nullable=False),
        sa.Column("coach_number", sa.String(length=5), nullable=False),
        sa.Column("train_class", sa.String(length=10), nullable=False),
        sa.Column("total_seats", sa.SmallInteger(), nullable=False),
        sa.Column("is_ac", sa.Boolean(), nullable=False),
        sa.Column("coach_position", sa.SmallInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["train_id"], ["railmind_be.trains.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_id", "coach_number", name="uq_coaches_train_coach"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_coaches_train_class"),
        "coaches",
        ["train_class"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_coaches_train_id"),
        "coaches",
        ["train_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "seat_inventories",
        sa.Column("train_id", sa.UUID(), nullable=False),
        sa.Column("journey_date", sa.Date(), nullable=False),
        sa.Column("train_class", sa.String(length=5), nullable=False),
        sa.Column("quota", sa.String(length=5), nullable=False),
        sa.Column("total_confirmed_seats", sa.SmallInteger(), nullable=False),
        sa.Column("available_confirmed_seats", sa.SmallInteger(), nullable=False),
        sa.Column("total_rac_berths", sa.SmallInteger(), nullable=False),
        sa.Column("total_rac_slots", sa.SmallInteger(), nullable=False),
        sa.Column("available_rac_slots", sa.SmallInteger(), nullable=False),
        sa.Column("wl_count", sa.SmallInteger(), nullable=False),
        sa.Column("wl_max", sa.SmallInteger(), nullable=False),
        sa.Column("is_chart_prepared", sa.Boolean(), nullable=False),
        sa.Column("chart_prepared_at", sa.DateTime(), nullable=True),
        sa.Column("quota_released_seats", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "available_confirmed_seats <= total_confirmed_seats",
            name="ck_seat_inv_cnf_lte_total",
        ),
        sa.CheckConstraint(
            "available_confirmed_seats >= 0", name="ck_seat_inv_cnf_gte_zero"
        ),
        sa.CheckConstraint(
            "available_rac_slots <= total_rac_slots", name="ck_seat_inv_rac_lte_total"
        ),
        sa.CheckConstraint("available_rac_slots >= 0", name="ck_seat_inv_rac_gte_zero"),
        sa.CheckConstraint(
            "total_rac_slots = total_rac_berths * 2",
            name="ck_seat_inv_rac_slots_eq_berths_x2",
        ),
        sa.CheckConstraint("wl_count <= wl_max", name="ck_seat_inv_wl_lte_max"),
        sa.CheckConstraint("wl_count >= 0", name="ck_seat_inv_wl_gte_zero"),
        sa.ForeignKeyConstraint(
            ["train_id"], ["railmind_be.trains.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "train_id",
            "journey_date",
            "train_class",
            "quota",
            name="uq_seat_inv_train_date_class_quota",
        ),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_seat_inventories_journey_date"),
        "seat_inventories",
        ["journey_date"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_seat_inventories_train_id"),
        "seat_inventories",
        ["train_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        "ix_seat_inv_date_class_quota",
        "seat_inventories",
        ["journey_date", "train_class", "quota"],
        unique=False,
        schema="railmind_be",
    )
    op.create_table(
        "seats",
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("seat_number", sa.SmallInteger(), nullable=False),
        sa.Column("berth_type", sa.String(length=5), nullable=False),
        sa.Column("is_rac_berth", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"], ["railmind_be.coaches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coach_id", "seat_number", name="uq_seats_coach_seat"),
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_seats_coach_id"),
        "seats",
        ["coach_id"],
        unique=False,
        schema="railmind_be",
    )

    # ── stations: add new columns ──────────────────────────────────────────
    # city added as nullable first so existing rows don't violate NOT NULL,
    # then backfilled, then tightened to NOT NULL.
    op.add_column(
        "stations",
        sa.Column("city", sa.String(length=60), nullable=True),
        schema="railmind_be",
    )
    op.execute("UPDATE railmind_be.stations SET city = 'UNKNOWN'")
    op.alter_column("stations", "city", nullable=False, schema="railmind_be")
    # FIX: removed duplicate op.add_column for 'city' that was here — caused DuplicateColumn error

    # Every NOT NULL column on an existing table must follow:
    #   1. add as nullable  →  2. backfill  →  3. alter to NOT NULL
    # Skipping step 1+2 causes NotNullViolation on any existing rows.

    op.add_column(
        "stations",
        sa.Column("state", sa.String(length=60), nullable=True),
        schema="railmind_be",
    )
    op.execute("UPDATE railmind_be.stations SET state = 'UNKNOWN'")
    op.alter_column("stations", "state", nullable=False, schema="railmind_be")

    # nullable columns — no backfill needed
    op.add_column(
        "stations",
        sa.Column("zone", sa.String(length=10), nullable=True),
        schema="railmind_be",
    )
    op.add_column(
        "stations",
        sa.Column("latitude", sa.Float(), nullable=True),
        schema="railmind_be",
    )
    op.add_column(
        "stations",
        sa.Column("longitude", sa.Float(), nullable=True),
        schema="railmind_be",
    )

    op.add_column(
        "stations",
        sa.Column("is_junction", sa.Boolean(), nullable=True),
        schema="railmind_be",
    )
    op.execute("UPDATE railmind_be.stations SET is_junction = false")
    op.alter_column("stations", "is_junction", nullable=False, schema="railmind_be")

    op.add_column(
        "stations",
        sa.Column("is_remote_location", sa.Boolean(), nullable=True),
        schema="railmind_be",
    )
    op.execute("UPDATE railmind_be.stations SET is_remote_location = false")
    op.alter_column(
        "stations", "is_remote_location", nullable=False, schema="railmind_be"
    )
    op.create_index(
        op.f("ix_railmind_be_stations_city"),
        "stations",
        ["city"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_stations_is_remote_location"),
        "stations",
        ["is_remote_location"],
        unique=False,
        schema="railmind_be",
    )

    # ── train_stations: add day_number, reindex ────────────────────────────
    op.add_column(
        "train_stations",
        sa.Column("day_number", sa.SmallInteger(), nullable=True),
        schema="railmind_be",
    )
    op.execute("UPDATE railmind_be.train_stations SET day_number = 1")
    op.alter_column(
        "train_stations", "day_number", nullable=False, schema="railmind_be"
    )
    op.drop_index(
        op.f("ix_train_stations_station_id"),
        table_name="train_stations",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_train_stations_train_id"),
        table_name="train_stations",
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_train_stations_station_id"),
        "train_stations",
        ["station_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_railmind_be_train_stations_train_id"),
        "train_stations",
        ["train_id"],
        unique=False,
        schema="railmind_be",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_railmind_be_train_stations_train_id"),
        table_name="train_stations",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_train_stations_station_id"),
        table_name="train_stations",
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_train_stations_train_id"),
        "train_stations",
        ["train_id"],
        unique=False,
        schema="railmind_be",
    )
    op.create_index(
        op.f("ix_train_stations_station_id"),
        "train_stations",
        ["station_id"],
        unique=False,
        schema="railmind_be",
    )
    op.drop_column("train_stations", "day_number", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_stations_is_remote_location"),
        table_name="stations",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_stations_city"),
        table_name="stations",
        schema="railmind_be",
    )
    op.drop_column("stations", "is_remote_location", schema="railmind_be")
    op.drop_column("stations", "is_junction", schema="railmind_be")
    op.drop_column("stations", "longitude", schema="railmind_be")
    op.drop_column("stations", "latitude", schema="railmind_be")
    op.drop_column("stations", "zone", schema="railmind_be")
    op.drop_column("stations", "state", schema="railmind_be")
    op.drop_column("stations", "city", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_seats_coach_id"), table_name="seats", schema="railmind_be"
    )
    op.drop_table("seats", schema="railmind_be")
    op.drop_index(
        "ix_seat_inv_date_class_quota",
        table_name="seat_inventories",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_seat_inventories_train_id"),
        table_name="seat_inventories",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_seat_inventories_journey_date"),
        table_name="seat_inventories",
        schema="railmind_be",
    )
    op.drop_table("seat_inventories", schema="railmind_be")
    op.drop_index(
        op.f("ix_railmind_be_coaches_train_id"),
        table_name="coaches",
        schema="railmind_be",
    )
    op.drop_index(
        op.f("ix_railmind_be_coaches_train_class"),
        table_name="coaches",
        schema="railmind_be",
    )
    op.drop_table("coaches", schema="railmind_be")
    # ### end Alembic commands ###
